// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/weather-redesign/BoldTypographic.tsx": () => import("../components/mockups/weather-redesign/BoldTypographic.tsx"),
  "./components/mockups/weather-redesign/GlassMinimal.tsx": () => import("../components/mockups/weather-redesign/GlassMinimal.tsx"),
  "./components/mockups/weather-redesign/SoftBento.tsx": () => import("../components/mockups/weather-redesign/SoftBento.tsx")
};
