// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/weather-redesign/BentoCoastal.tsx": () => import("../components/mockups/weather-redesign/BentoCoastal.tsx"),
  "./components/mockups/weather-redesign/BentoMidnight.tsx": () => import("../components/mockups/weather-redesign/BentoMidnight.tsx"),
  "./components/mockups/weather-redesign/BentoSunrise.tsx": () => import("../components/mockups/weather-redesign/BentoSunrise.tsx"),
  "./components/mockups/weather-redesign/BoldBrutalist.tsx": () => import("../components/mockups/weather-redesign/BoldBrutalist.tsx"),
  "./components/mockups/weather-redesign/BoldEditorial.tsx": () => import("../components/mockups/weather-redesign/BoldEditorial.tsx"),
  "./components/mockups/weather-redesign/BoldNeon.tsx": () => import("../components/mockups/weather-redesign/BoldNeon.tsx"),
  "./components/mockups/weather-redesign/BoldTypographic.tsx": () => import("../components/mockups/weather-redesign/BoldTypographic.tsx"),
  "./components/mockups/weather-redesign/CoastalCandy.tsx": () => import("../components/mockups/weather-redesign/CoastalCandy.tsx"),
  "./components/mockups/weather-redesign/CoastalDoodle.tsx": () => import("../components/mockups/weather-redesign/CoastalDoodle.tsx"),
  "./components/mockups/weather-redesign/CoastalJelly.tsx": () => import("../components/mockups/weather-redesign/CoastalJelly.tsx"),
  "./components/mockups/weather-redesign/GlassMinimal.tsx": () => import("../components/mockups/weather-redesign/GlassMinimal.tsx"),
  "./components/mockups/weather-redesign/SeussClassic.tsx": () => import("../components/mockups/weather-redesign/SeussClassic.tsx"),
  "./components/mockups/weather-redesign/SeussHatCat.tsx": () => import("../components/mockups/weather-redesign/SeussHatCat.tsx"),
  "./components/mockups/weather-redesign/SeussLorax.tsx": () => import("../components/mockups/weather-redesign/SeussLorax.tsx"),
  "./components/mockups/weather-redesign/SoftBento.tsx": () => import("../components/mockups/weather-redesign/SoftBento.tsx")
};
